name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Altere para a branch que você deseja fazer o deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Altere para a versão do Node.js que você usa

    - name: Install dependencies
      run: npm install

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure App Service
      run: |
        az group create --name minha-api-rg --location eastus
        az appservice plan create --name minha-api-plan --resource-group minha-api-rg --sku B1 --is-linux
        az webapp create --resource-group minha-api-rg --plan minha-api-plan --name minha-api-app --runtime "NODE|14-lts"

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'minha-api-app'  
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}